[package]
name = "gueiz"
version.workspace = true
edition.workspace = true

[dependencies]
bytemuck.workspace = true
env_logger.workspace = true
gueiz-2d.workspace = true
gueiz-3d.workspace = true
gueiz-window.workspace = true
log.workspace = true
pollster.workspace = true
raw-window-handle.workspace = true
wgpu.workspace = true
winit.workspace = true
